/*
 * Copyright (c) 2024 Sergey Alexeev
 * Email: sergeyalexeev@yahoo.com
 *
 *  Licensed under the MIT License. See the [LICENSE](https://opensource.org/licenses/MIT) file for details.
 */

package grpc

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/gorundebug/servicelib/api"
	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment/tracing"
)

const pendingRotationInterval = 30 * time.Second

// Sender allows the handler to send a request to the gRPC stream.
// For bidi and client streaming Send goes directly to the gRPC stream;
// for server streaming and unary it captures the request so the framework
// can open the stream / make the call after ConsumeMessage returns.
type Sender[ReqT any] interface {
	Send(req ReqT) error
}

// ResultContext is passed to ConsumeMessage for bidi and client streaming sinks.
// Call Done() to signal that no more requests will be sent on this stream;
// the framework will then close the send side and await the final response(s).
// For unary and server-streaming Done() is a no-op.
type ResultContext interface {
	Done()
}

type nopResultContext struct{}

func (nopResultContext) Done() {}

// StreamContext bundles the result stream, output collector, and error collector
// that are passed to every EndpointHandler lifecycle method.
// Stream() provides serde access for the result type R.
type StreamContext[T, R, E any] = runtime.SinkStreamContext[T, R, E]

// EndpointHandler handles gRPC sink calls for a single endpoint.
//
// Pipeline lifecycle — unary and server-streaming (one gRPC call per Consume):
//
//	BeginRequest → ConsumeMessage → [gRPC call] → HandleResponse (0..N) → EndRequest
//
// Pipeline lifecycle — bidi and client-streaming (one gRPC stream per streamID):
//
//	BeginRequest (once per streamID)
//	ConsumeMessage (called for each Consume with the same streamID)
//	  └─ resultCtx.Done() signals no more requests; framework closes send side
//	HandleResponse (0..N, called as responses arrive)
//	EndRequest (once, after the stream is closed)
//
// BeginRequest initialises per-stream handler state. If it returns a non-nil error
// the framework will NOT call ConsumeMessage, HandleResponse, or EndRequest.
// BeginRequest is responsible for releasing any resources it acquired before
// returning the error.
//
// ConsumeMessage converts value T into a gRPC request and calls sender.Send.
// For bidi/client-streaming the handler calls resultCtx.Done() on the last message
// to signal end-of-stream. For unary/server-streaming resultCtx is a no-op.
// Returning a non-nil error causes the framework to call Done() and EndRequest.
//
// HandleResponse is called for each response received from the gRPC server.
// It should push results into the pipeline via sc.Collect.Out.
// sc.Stream provides serde access for type R.
// Returning a non-nil error aborts further Recv processing.
//
// EndRequest finalises the stream after all responses have been received (or on
// error). Its error argument is the first non-nil error encountered; nil on the
// happy path. Unlike gRPC source handlers, EndRequest does not return an error.
//
// Thread safety: BeginRequest, ConsumeMessage, and EndRequest are called
// sequentially per stream. HandleResponse may be called concurrently with
// ConsumeMessage (bidi). Implementations must synchronise HandlerState access
// accordingly.
type EndpointHandler[HandlerState, ReqT, ResR, T, R, E any] interface {
	BeginRequest(ctx context.Context, sc StreamContext[T, R, E]) (context.Context, HandlerState, error)
	// ConsumeMessage converts value T to ReqT and calls sender.Send.
	// resultCtx.Done() signals end-of-stream for bidi/client-streaming.
	ConsumeMessage(ctx context.Context, sc StreamContext[T, R, E], handlerState HandlerState, value T, sender Sender[ReqT], resultCtx ResultContext) error
	// HandleResponse converts a received ResR and pushes it to the pipeline
	// via sc.Collect.Out. sc.Stream provides serde access for type R.
	// Return non-nil to abort further Recv processing.
	HandleResponse(ctx context.Context, sc StreamContext[T, R, E], handlerState HandlerState, response ResR) error
	EndRequest(ctx context.Context, sc StreamContext[T, R, E], err error, handlerState HandlerState)
}

// ClientFunction types match the method signatures generated by protoc for each streaming variant.
// Pass the gRPC client method directly (wrapped in a closure to drop grpc.CallOption if needed).
type (
	// NoStreamingClientFunction is a unary gRPC call: one request, one response.
	NoStreamingClientFunction[ReqT, ResR any] func(ctx context.Context, req ReqT) (ResR, error)

	// ServerStreamingClientFunction opens a server-streaming call with a single request.
	ServerStreamingClientFunction[ReqT, ResR any] func(ctx context.Context, req ReqT) (ServerStreamingGRPCStream[ResR], error)

	// ClientStreamingClientFunction opens a client-streaming call; the request is sent via the stream.
	ClientStreamingClientFunction[ReqT, ResR any] func(ctx context.Context) (ClientStreamingGRPCStream[ReqT, ResR], error)

	// BidiStreamingClientFunction opens a bidi-streaming call; requests and responses flow through the stream.
	BidiStreamingClientFunction[ReqT, ResR any] func(ctx context.Context) (BidiStreamingGRPCStream[ReqT, ResR], error)
)

// grpcSender forwards Send calls to the underlying gRPC stream.
type grpcSender[ReqT any] struct {
	sendFn func(ReqT) error
	span   tracing.Span
}

func (s *grpcSender[ReqT]) Send(req ReqT) error {
	err := s.sendFn(req)
	if err != nil {
		tracing.SpanError(s.span, err)
		tracing.SpanEvent(s.span, "send.error", tracing.StringAttr("error", err.Error()))
	} else {
		tracing.SpanEvent(s.span, "send")
	}
	return err
}

// requestSender stores the request without sending immediately.
// Used for unary and server-streaming where the framework needs the request
// before opening the stream.
type requestSender[ReqT any] struct {
	req ReqT
}

func (s *requestSender[ReqT]) Send(req ReqT) error {
	s.req = req
	return nil
}

// grpcTypedSinkEndpointConsumer is the base struct for all gRPC sink consumers.
// It stores the typed stream, endpoint, and a cached stream context.
type grpcTypedSinkEndpointConsumer[T, R, E any] struct {
	endpoint runtime.SinkEndpoint
	stream   runtime.TypedSinkStreamWithResult[T, R, E]
	sc       StreamContext[T, R, E]
	tracer   tracing.Tracer
}

func (ec *grpcTypedSinkEndpointConsumer[T, R, E]) Endpoint() runtime.SinkEndpoint {
	return ec.endpoint
}

// — infrastructure ————————————————————————————————————————

type grpcSinkOutputDataSink interface {
	runtime.DataSink
	WaitGroup() *sync.WaitGroup
}

type grpcSinkEndpointConsumer interface {
	runtime.OutputEndpointConsumer
	Start(context.Context) error
	Stop(context.Context)
}

type grpcSinkEndpointIface interface {
	runtime.SinkEndpoint
	Start(context.Context) error
	Stop(context.Context)
}

type grpcSinkDataSink struct {
	*runtime.OutputDataSink
	wg sync.WaitGroup
}

type grpcSinkEndpoint struct {
	*runtime.DataSinkEndpoint
	consumer grpcSinkEndpointConsumer
}

func (ds *grpcSinkDataSink) WaitGroup() *sync.WaitGroup {
	return &ds.wg
}

func (ds *grpcSinkDataSink) Start(ctx context.Context) error {
	endpoints := ds.GetEndpoints()
	length := endpoints.Len()
	for i := 0; i < length; i++ {
		if err := endpoints.At(i).(grpcSinkEndpointIface).Start(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (ds *grpcSinkDataSink) Stop(ctx context.Context) {
	endpoints := ds.GetEndpoints()
	length := endpoints.Len()
	for i := 0; i < length; i++ {
		ds.wg.Add(1)
		go func(ep grpcSinkEndpointIface) {
			defer ds.wg.Done()
			ep.Stop(ctx)
		}(endpoints.At(i).(grpcSinkEndpointIface))
	}
	c := make(chan struct{})
	go func() {
		defer close(c)
		ds.wg.Wait()
	}()
	select {
	case <-c:
	case <-ctx.Done():
		ds.OnStopTimeout(ctx)
	}
}

func (ep *grpcSinkEndpoint) Start(ctx context.Context) error {
	return ep.consumer.Start(ctx)
}

func (ep *grpcSinkEndpoint) Stop(ctx context.Context) {
	ep.consumer.Stop(ctx)
}

func getOrCreateGRPCSinkDataSink(id int, env runtime.RuntimeEnvironment) (runtime.DataSink, error) {
	dataSink := env.GetDataSink(id)
	if dataSink != nil {
		return dataSink, nil
	}
	cfg := env.RuntimeConfig().GetDataConnectorByID(id)
	if cfg == nil {
		return nil, fmt.Errorf("config for datasink with id=%d not found", id)
	}
	dsCfg, ok := cfg.(*config.GrpcDataConnectorConfig)
	if !ok || dsCfg.Implementation != api.DataConnectorImplementationGoogleGRPC {
		return nil, fmt.Errorf("invalid config type for datasink %q", cfg.GetName())
	}
	outputDS, err := runtime.MakeOutputDataSink(cfg, env)
	if err != nil {
		return nil, err
	}
	ds := &grpcSinkDataSink{
		OutputDataSink: outputDS,
	}
	var outputDataSink grpcSinkOutputDataSink = ds
	env.AddDataSink(outputDataSink)
	return ds, nil
}

func createGRPCSinkEndpoint(id int, env runtime.RuntimeEnvironment) (*grpcSinkEndpoint, error) {
	cfg := env.RuntimeConfig().GetEndpointConfigByID(id)
	if cfg == nil {
		return nil, fmt.Errorf("config for endpoint with id=%d not found", id)
	}
	epCfg, ok := cfg.(*config.GrpcEndpointConfig)
	if !ok {
		return nil, fmt.Errorf("invalid config type for endpoint %q", cfg.GetName())
	}
	dataSink, err := getOrCreateGRPCSinkDataSink(epCfg.IdDataConnector, env)
	if err != nil {
		return nil, err
	}
	endpoint := dataSink.GetEndpoint(id)
	if endpoint != nil {
		return nil, fmt.Errorf("endpoint %q already exists", epCfg.GetName())
	}
	sinkEndpoint, err := runtime.MakeDataSinkEndpoint(dataSink, id, env)
	if err != nil {
		return nil, err
	}
	ep := &grpcSinkEndpoint{
		DataSinkEndpoint: sinkEndpoint,
	}
	dataSink.AddEndpoint(ep)
	return ep, nil
}
