//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
)

// Defines values for CallSemantics.
const (
	CallSemanticsDurableCall      CallSemantics = 6
	CallSemanticsFunctionCall     CallSemantics = 2
	CallSemanticsInherited        CallSemantics = 1
	CallSemanticsParallelCall     CallSemantics = 5
	CallSemanticsPriorityTaskPool CallSemantics = 4
	CallSemanticsTaskPool         CallSemantics = 3
	CallSemanticsUndefined        CallSemantics = 0
)

// Defines values for DataConnectorImplementation.
const (
	DataConnectorImplementationAioHTTP                  DataConnectorImplementation = "aiohttp"
	DataConnectorImplementationAioKafka                 DataConnectorImplementation = "aiokafka"
	DataConnectorImplementationAsioGRPC                 DataConnectorImplementation = "asio/grpc"
	DataConnectorImplementationBoostBeastHTTP           DataConnectorImplementation = "boost/beast-http"
	DataConnectorImplementationConfluentKafkaJavaScript DataConnectorImplementation = "confluent/kafka-javascript"
	DataConnectorImplementationCppLibcron               DataConnectorImplementation = "cpp/libcron"
	DataConnectorImplementationFunction                 DataConnectorImplementation = "function"
	DataConnectorImplementationGoGocron                 DataConnectorImplementation = "go/gocron"
	DataConnectorImplementationGoogleGRPC               DataConnectorImplementation = "google/grpc"
	DataConnectorImplementationGrpcJS                   DataConnectorImplementation = "grpc/grpc-js"
	DataConnectorImplementationIBMsarama                DataConnectorImplementation = "IBM/Sarama"
	DataConnectorImplementationLibrdkafka               DataConnectorImplementation = "librdkafka"
	DataConnectorImplementationNetHTTP                  DataConnectorImplementation = "net/http"
	DataConnectorImplementationNodeCroner               DataConnectorImplementation = "node/croner"
	DataConnectorImplementationNodeHTTP                 DataConnectorImplementation = "node/http"
	DataConnectorImplementationPythonAPScheduler        DataConnectorImplementation = "python/apscheduler"
	DataConnectorImplementationRustAxum                 DataConnectorImplementation = "rust/axum"
	DataConnectorImplementationRustCroner               DataConnectorImplementation = "rust/croner"
	DataConnectorImplementationRustRdkafka              DataConnectorImplementation = "rust/rdkafka"
	DataConnectorImplementationRustTonic                DataConnectorImplementation = "rust/tonic"
	DataConnectorImplementationTemporalGo               DataConnectorImplementation = "temporal/go"
	DataConnectorImplementationTemporalPython           DataConnectorImplementation = "temporal/python"
	DataConnectorImplementationTemporalTypeScript       DataConnectorImplementation = "temporal/typescript"
	DataConnectorImplementationUndefined                DataConnectorImplementation = ""
	DataConnectorImplementationUserverGRPC              DataConnectorImplementation = "userver/grpc"
	DataConnectorImplementationUserverHTTP              DataConnectorImplementation = "userver/http"
	DataConnectorImplementationUserverKafka             DataConnectorImplementation = "userver/kafka"
)

// Defines values for DataConnectorType.
const (
	DataConnectorTypeCron      DataConnectorType = 5
	DataConnectorTypeCustom    DataConnectorType = 4
	DataConnectorTypeGRPC      DataConnectorType = 2
	DataConnectorTypeHTTP      DataConnectorType = 1
	DataConnectorTypeKafka     DataConnectorType = 3
	DataConnectorTypeTemporal  DataConnectorType = 6
	DataConnectorTypeUndefined DataConnectorType = 0
)

// Defines values for DataType.
const (
	DataTypeAny             DataType = "any"
	DataTypeArray           DataType = "array"
	DataTypeBoolean         DataType = "boolean"
	DataTypeByte            DataType = "byte"
	DataTypeChar            DataType = "char"
	DataTypeCustom          DataType = "custom"
	DataTypeDouble          DataType = "double"
	DataTypeError           DataType = "error"
	DataTypeFloat           DataType = "float"
	DataTypeInt             DataType = "int"
	DataTypeInt16           DataType = "int16"
	DataTypeInt32           DataType = "int32"
	DataTypeInt64           DataType = "int64"
	DataTypeInt8            DataType = "int8"
	DataTypeMap             DataType = "map"
	DataTypeScheduleTrigger DataType = "schedule trigger"
	DataTypeString          DataType = "string"
	DataTypeStruct          DataType = "struct"
	DataTypeUint            DataType = "uint"
	DataTypeUint16          DataType = "uint16"
	DataTypeUint32          DataType = "uint32"
	DataTypeUint64          DataType = "uint64"
	DataTypeUint8           DataType = "uint8"
	DataTypeUndefined       DataType = ""
	DataTypeUnicodeChar     DataType = "unicode char"
	DataTypeUnicodeString   DataType = "unicode string"
)

// Defines values for Environment.
const (
	EnvironmentDebug      Environment = "debug"
	EnvironmentLocal      Environment = "local"
	EnvironmentProduction Environment = "production"
	EnvironmentStaging    Environment = "staging"
	EnvironmentUndefined  Environment = ""
)

// Defines values for GrpcMethodType.
const (
	GrpcMethodTypeBidirectionalStreaming GrpcMethodType = 5
	GrpcMethodTypeClientStreaming        GrpcMethodType = 2
	GrpcMethodTypeNoStreaming            GrpcMethodType = 1
	GrpcMethodTypeServerStreaming        GrpcMethodType = 4
	GrpcMethodTypeUndefined              GrpcMethodType = 0
)

// Defines values for HTTPMethodType.
const (
	HTTPMethodTypeGET       HTTPMethodType = "GET"
	HTTPMethodTypePOST      HTTPMethodType = "POST"
	HTTPMethodTypeUndefined HTTPMethodType = ""
)

// Defines values for JoinStorageType.
const (
	JoinStorageTypeAerospike JoinStorageType = 3
	JoinStorageTypeHashMap   JoinStorageType = 1
	JoinStorageTypeRocksDB   JoinStorageType = 2
	JoinStorageTypeUndefined JoinStorageType = 0
)

// Defines values for JoinType.
const (
	JoinTypeInner     JoinType = 1
	JoinTypeLeft      JoinType = 2
	JoinTypeOuter     JoinType = 4
	JoinTypeRight     JoinType = 3
	JoinTypeUndefined JoinType = 0
)

// Defines values for KafkaSaslMechanism.
const (
	PLAIN       KafkaSaslMechanism = "PLAIN"
	SCRAMSHA256 KafkaSaslMechanism = "SCRAM-SHA-256"
	SCRAMSHA512 KafkaSaslMechanism = "SCRAM-SHA-512"
)

// Defines values for KafkaSecurityProtocol.
const (
	PLAINTEXT     KafkaSecurityProtocol = "PLAINTEXT"
	SASLPLAINTEXT KafkaSecurityProtocol = "SASL_PLAINTEXT"
	SASLSSL       KafkaSecurityProtocol = "SASL_SSL"
)

// Defines values for KubernetesWorkloadType.
const (
	Deployment  KubernetesWorkloadType = "Deployment"
	StatefulSet KubernetesWorkloadType = "StatefulSet"
)

// Defines values for LogLevel.
const (
	LogLevelCRITICAL  LogLevel = "CRITICAL"
	LogLevelDEBUG     LogLevel = "DEBUG"
	LogLevelERROR     LogLevel = "ERROR"
	LogLevelFATAL     LogLevel = "FATAL"
	LogLevelINFO      LogLevel = "INFO"
	LogLevelUndefined LogLevel = ""
	LogLevelWARNING   LogLevel = "WARNING"
)

// Defines values for ProcessPattern.
const (
	ProcessPatternCollect   ProcessPattern = 2
	ProcessPatternExecute   ProcessPattern = 1
	ProcessPatternUndefined ProcessPattern = 0
)

// Defines values for ProgrammingLanguage.
const (
	ProgrammingLanguageCppBoost   ProgrammingLanguage = 5
	ProgrammingLanguageCppUserver ProgrammingLanguage = 2
	ProgrammingLanguageGoLang     ProgrammingLanguage = 1
	ProgrammingLanguagePython     ProgrammingLanguage = 3
	ProgrammingLanguageRust       ProgrammingLanguage = 4
	ProgrammingLanguageTypeScript ProgrammingLanguage = 6
	ProgrammingLanguageUndefined  ProgrammingLanguage = 0
)

// Defines values for ScheduleMissedRunPolicy.
const (
	ScheduleMissedRunPolicyFireOnce ScheduleMissedRunPolicy = "FireOnce"
	ScheduleMissedRunPolicySkip     ScheduleMissedRunPolicy = "Skip"
)

// Defines values for ScheduleOverlapPolicy.
const (
	ScheduleOverlapPolicyAllow ScheduleOverlapPolicy = "Allow"
	ScheduleOverlapPolicySkip  ScheduleOverlapPolicy = "Skip"
)

// Defines values for TransformationType.
const (
	TransformationTypeCase            TransformationType = 12
	TransformationTypeCycleLink       TransformationType = 14
	TransformationTypeDelay           TransformationType = 16
	TransformationTypeError           TransformationType = 15
	TransformationTypeFilter          TransformationType = 3
	TransformationTypeFlatMap         TransformationType = 7
	TransformationTypeFlatMapIterable TransformationType = 8
	TransformationTypeInput           TransformationType = 1
	TransformationTypeJoin            TransformationType = 4
	TransformationTypeKeyBy           TransformationType = 9
	TransformationTypeMap             TransformationType = 2
	TransformationTypeMerge           TransformationType = 10
	TransformationTypeMultiJoin       TransformationType = 5
	TransformationTypeProcess         TransformationType = 6
	TransformationTypeSink            TransformationType = 13
	TransformationTypeSplit           TransformationType = 11
	TransformationTypeUndefined       TransformationType = 0
	TransformationTypeWhen            TransformationType = 17
)

// Defines values for TypeDefinitionFormat.
const (
	TypeDefinitionFormatCapNProto   TypeDefinitionFormat = 4
	TypeDefinitionFormatFlatBuffers TypeDefinitionFormat = 3
	TypeDefinitionFormatNative      TypeDefinitionFormat = 1
	TypeDefinitionFormatOpenAPI     TypeDefinitionFormat = 5
	TypeDefinitionFormatProtobuf    TypeDefinitionFormat = 2
	TypeDefinitionFormatUndefined   TypeDefinitionFormat = 0
)

// Defines values for UndefinedEnum.
const (
	Undefined UndefinedEnum = 0
)

// CallSemantics Delivery semantics for a stream link — controls how messages are passed between nodes.
// - `Inherited` (1): use the service's `defaultCallSemantics`
// - `FunctionCall` (2): synchronous in-goroutine call; lowest latency, no buffering
// - `TaskPool` (3): enqueue to a named FIFO worker pool; decouples producer from consumer
// - `PriorityTaskPool` (4): enqueue to a named priority worker pool; higher-priority messages are processed first
// - `ParallelCall` (5): spawn a new goroutine for each message; fully parallel, no pool overhead
// - `DurableCall` (6): execute the link as an independently identified Temporal Workflow/Activity operation
type CallSemantics int

// DataConnector Configuration for a connection to an external system. A data connector represents
// the external system itself (an HTTP server, a Kafka cluster, a gRPC server).
// Specific routes, topics, or methods are defined as `Endpoint` objects that
// reference this connector.
type DataConnector struct {
	// Address gRPC connection address.
	Address *string `json:"address,omitempty"`

	// ApiKey Temporal API key. Supply at runtime through an environment-backed override.
	ApiKey *string `json:"apiKey,omitempty"`

	// Async When true, the Kafka producer operates in async mode — messages are batched
	// and acknowledged asynchronously. Applies to Kafka sink connectors.
	Async *bool `json:"async,omitempty"`

	// Brokers Comma-separated list of Kafka broker addresses (e.g. `kafka1:9092,kafka2:9092`). Applies to Kafka connectors.
	Brokers *string `json:"brokers,omitempty"`

	// ConnectionsCount Number of independent transport connections used by a gRPC sink connector.
	ConnectionsCount *int `json:"connectionsCount,omitempty"`

	// CppBoostImplementation The specific library used to implement a data connector.
	// - `net/http`: Go standard library HTTP
	// - `function`: in-process custom connector (no network)
	// - `IBM/Sarama`: Sarama Kafka client
	// - `google/grpc`: official gRPC-Go library
	// - `userver/http`: userver HTTP
	// - `userver/grpc`: userver gRPC
	// - `userver/kafka`: userver Kafka
	// - `boost/beast-http`: Boost.Beast HTTP
	// - `asio/grpc`: asio-grpc
	// - `librdkafka`: librdkafka C++ client
	// - `aiohttp`: Python aiohttp
	// - `aiokafka`: Python aiokafka
	// - `rust/axum`: Rust axum HTTP
	// - `rust/tonic`: Rust tonic gRPC
	// - `rust/rdkafka`: Rust rdkafka Kafka client
	// - `node/http`: Node.js core HTTP transport
	// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
	// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
	// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
	CppBoostImplementation *DataConnectorImplementation `json:"cppBoostImplementation,omitempty"`

	// CppUserverImplementation The specific library used to implement a data connector.
	// - `net/http`: Go standard library HTTP
	// - `function`: in-process custom connector (no network)
	// - `IBM/Sarama`: Sarama Kafka client
	// - `google/grpc`: official gRPC-Go library
	// - `userver/http`: userver HTTP
	// - `userver/grpc`: userver gRPC
	// - `userver/kafka`: userver Kafka
	// - `boost/beast-http`: Boost.Beast HTTP
	// - `asio/grpc`: asio-grpc
	// - `librdkafka`: librdkafka C++ client
	// - `aiohttp`: Python aiohttp
	// - `aiokafka`: Python aiokafka
	// - `rust/axum`: Rust axum HTTP
	// - `rust/tonic`: Rust tonic gRPC
	// - `rust/rdkafka`: Rust rdkafka Kafka client
	// - `node/http`: Node.js core HTTP transport
	// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
	// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
	// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
	CppUserverImplementation *DataConnectorImplementation `json:"cppUserverImplementation,omitempty"`

	// DialTimeout Connection dial timeout in milliseconds. Applies to Kafka connectors.
	DialTimeout *float32 `json:"dialTimeout,omitempty"`

	// GoImplementation The specific library used to implement a data connector.
	// - `net/http`: Go standard library HTTP
	// - `function`: in-process custom connector (no network)
	// - `IBM/Sarama`: Sarama Kafka client
	// - `google/grpc`: official gRPC-Go library
	// - `userver/http`: userver HTTP
	// - `userver/grpc`: userver gRPC
	// - `userver/kafka`: userver Kafka
	// - `boost/beast-http`: Boost.Beast HTTP
	// - `asio/grpc`: asio-grpc
	// - `librdkafka`: librdkafka C++ client
	// - `aiohttp`: Python aiohttp
	// - `aiokafka`: Python aiokafka
	// - `rust/axum`: Rust axum HTTP
	// - `rust/tonic`: Rust tonic gRPC
	// - `rust/rdkafka`: Rust rdkafka Kafka client
	// - `node/http`: Node.js core HTTP transport
	// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
	// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
	// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
	GoImplementation *DataConnectorImplementation `json:"goImplementation,omitempty"`

	// Host Hostname or IP address. Applies to HTTP and gRPC connectors.
	Host *string `json:"host,omitempty"`

	// Id Unique identifier for this data connector within the topology.
	Id int `json:"id"`

	// Identity Temporal client and Worker identity. Applies to Temporal connectors.
	Identity *string `json:"identity,omitempty"`

	// Implementation The specific library used to implement a data connector.
	// - `net/http`: Go standard library HTTP
	// - `function`: in-process custom connector (no network)
	// - `IBM/Sarama`: Sarama Kafka client
	// - `google/grpc`: official gRPC-Go library
	// - `userver/http`: userver HTTP
	// - `userver/grpc`: userver gRPC
	// - `userver/kafka`: userver Kafka
	// - `boost/beast-http`: Boost.Beast HTTP
	// - `asio/grpc`: asio-grpc
	// - `librdkafka`: librdkafka C++ client
	// - `aiohttp`: Python aiohttp
	// - `aiokafka`: Python aiokafka
	// - `rust/axum`: Rust axum HTTP
	// - `rust/tonic`: Rust tonic gRPC
	// - `rust/rdkafka`: Rust rdkafka Kafka client
	// - `node/http`: Node.js core HTTP transport
	// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
	// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
	// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
	Implementation *DataConnectorImplementation `json:"implementation,omitempty"`

	// MaxConcurrentActivities Maximum Activity slots owned by this Temporal connector's Worker.
	MaxConcurrentActivities *int `json:"maxConcurrentActivities,omitempty"`

	// MaxConcurrentWorkflows Maximum Workflow slots owned by this Temporal connector's Worker.
	MaxConcurrentWorkflows *int `json:"maxConcurrentWorkflows,omitempty"`

	// Module Contract module containing generated gRPC protobuf types for this connector.
	// Used to resolve the correct generated bindings for each target language.
	// Applies to gRPC connectors.
	Module *string `json:"module,omitempty"`

	// Name Human-readable connector name used in the visual designer and in generated server/client struct names.
	Name string `json:"name"`

	// Namespace Temporal namespace. Applies to Temporal connectors.
	Namespace *string `json:"namespace,omitempty"`

	// Password Kafka SASL password. Supply at runtime through the generated environment override.
	Password *string `json:"password,omitempty"`

	// Port Port number. Applies to HTTP and gRPC connectors.
	Port *int `json:"port,omitempty"`

	// PythonImplementation The specific library used to implement a data connector.
	// - `net/http`: Go standard library HTTP
	// - `function`: in-process custom connector (no network)
	// - `IBM/Sarama`: Sarama Kafka client
	// - `google/grpc`: official gRPC-Go library
	// - `userver/http`: userver HTTP
	// - `userver/grpc`: userver gRPC
	// - `userver/kafka`: userver Kafka
	// - `boost/beast-http`: Boost.Beast HTTP
	// - `asio/grpc`: asio-grpc
	// - `librdkafka`: librdkafka C++ client
	// - `aiohttp`: Python aiohttp
	// - `aiokafka`: Python aiokafka
	// - `rust/axum`: Rust axum HTTP
	// - `rust/tonic`: Rust tonic gRPC
	// - `rust/rdkafka`: Rust rdkafka Kafka client
	// - `node/http`: Node.js core HTTP transport
	// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
	// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
	// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
	PythonImplementation *DataConnectorImplementation `json:"pythonImplementation,omitempty"`

	// RustImplementation The specific library used to implement a data connector.
	// - `net/http`: Go standard library HTTP
	// - `function`: in-process custom connector (no network)
	// - `IBM/Sarama`: Sarama Kafka client
	// - `google/grpc`: official gRPC-Go library
	// - `userver/http`: userver HTTP
	// - `userver/grpc`: userver gRPC
	// - `userver/kafka`: userver Kafka
	// - `boost/beast-http`: Boost.Beast HTTP
	// - `asio/grpc`: asio-grpc
	// - `librdkafka`: librdkafka C++ client
	// - `aiohttp`: Python aiohttp
	// - `aiokafka`: Python aiokafka
	// - `rust/axum`: Rust axum HTTP
	// - `rust/tonic`: Rust tonic gRPC
	// - `rust/rdkafka`: Rust rdkafka Kafka client
	// - `node/http`: Node.js core HTTP transport
	// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
	// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
	// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
	RustImplementation *DataConnectorImplementation `json:"rustImplementation,omitempty"`

	// SaslMechanism Kafka SASL authentication mechanism.
	SaslMechanism *KafkaSaslMechanism `json:"saslMechanism,omitempty"`

	// SecurityProtocol Kafka client transport security protocol.
	SecurityProtocol *KafkaSecurityProtocol `json:"securityProtocol,omitempty"`

	// TlsCaFile Path to a PEM CA bundle mounted into the service container.
	TlsCaFile *string `json:"tlsCaFile,omitempty"`

	// TlsCertFile Path to a PEM client certificate for Temporal mTLS.
	TlsCertFile *string `json:"tlsCertFile,omitempty"`

	// TlsEnabled Enables TLS for a Temporal connector.
	TlsEnabled *bool `json:"tlsEnabled,omitempty"`

	// TlsKeyFile Path to the PEM private key paired with tlsCertFile.
	TlsKeyFile *string `json:"tlsKeyFile,omitempty"`

	// TlsServerName Expected TLS server name for a Temporal connector.
	TlsServerName *string `json:"tlsServerName,omitempty"`

	// Type Type of external system the data connector connects to.
	// - `HTTP` (1): HTTP server or client
	// - `gRPC` (2): gRPC server or client
	// - `Kafka` (3): Kafka cluster
	// - `Custom` (4): in-process local connector for testing or internal pipelines
	// - `Cron` (5): process-local cron scheduler
	// - `Temporal` (6): Temporal Service connection, Workers, Schedules, and durable jobs
	Type DataConnectorType `json:"type"`

	// TypeScriptImplementation The specific library used to implement a data connector.
	// - `net/http`: Go standard library HTTP
	// - `function`: in-process custom connector (no network)
	// - `IBM/Sarama`: Sarama Kafka client
	// - `google/grpc`: official gRPC-Go library
	// - `userver/http`: userver HTTP
	// - `userver/grpc`: userver gRPC
	// - `userver/kafka`: userver Kafka
	// - `boost/beast-http`: Boost.Beast HTTP
	// - `asio/grpc`: asio-grpc
	// - `librdkafka`: librdkafka C++ client
	// - `aiohttp`: Python aiohttp
	// - `aiokafka`: Python aiokafka
	// - `rust/axum`: Rust axum HTTP
	// - `rust/tonic`: Rust tonic gRPC
	// - `rust/rdkafka`: Rust rdkafka Kafka client
	// - `node/http`: Node.js core HTTP transport
	// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
	// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
	// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
	TypeScriptImplementation *DataConnectorImplementation `json:"typeScriptImplementation,omitempty"`

	// UseDedicatedListener When true, this HTTP connector starts its own dedicated listener.
	// When false, it shares the service's default HTTP server.
	// Applies to HTTP source connectors.
	UseDedicatedListener *bool `json:"useDedicatedListener,omitempty"`

	// UsePartitioner When true, a custom Kafka partitioner is used for produced messages.
	// The partitioner function is included in the generated stub.
	// Applies to Kafka sink connectors.
	UsePartitioner *bool `json:"usePartitioner,omitempty"`

	// Username Kafka SASL username. Supply at runtime through the generated environment override.
	Username *string `json:"username,omitempty"`

	// Version Kafka protocol version expected by the broker (e.g. `2.8.0`). Applies to Kafka connectors.
	Version *string `json:"version,omitempty"`
}

// DataConnectorImplementation The specific library used to implement a data connector.
// - `net/http`: Go standard library HTTP
// - `function`: in-process custom connector (no network)
// - `IBM/Sarama`: Sarama Kafka client
// - `google/grpc`: official gRPC-Go library
// - `userver/http`: userver HTTP
// - `userver/grpc`: userver gRPC
// - `userver/kafka`: userver Kafka
// - `boost/beast-http`: Boost.Beast HTTP
// - `asio/grpc`: asio-grpc
// - `librdkafka`: librdkafka C++ client
// - `aiohttp`: Python aiohttp
// - `aiokafka`: Python aiokafka
// - `rust/axum`: Rust axum HTTP
// - `rust/tonic`: Rust tonic gRPC
// - `rust/rdkafka`: Rust rdkafka Kafka client
// - `node/http`: Node.js core HTTP transport
// - `grpc/grpc-js`: official pure-JavaScript gRPC transport
// - `confluent/kafka-javascript`: Confluent Kafka JavaScript client
// - `cpp/libcron`: libcron-backed UTC cron scheduler for C++ runtimes
type DataConnectorImplementation string

// DataConnectorType Type of external system the data connector connects to.
// - `HTTP` (1): HTTP server or client
// - `gRPC` (2): gRPC server or client
// - `Kafka` (3): Kafka cluster
// - `Custom` (4): in-process local connector for testing or internal pipelines
// - `Cron` (5): process-local cron scheduler
// - `Temporal` (6): Temporal Service connection, Workers, Schedules, and durable jobs
type DataConnectorType int

// DataType Primitive or composite data type for a named type. Controls generated serde code
// and type compatibility checks within the graph.
// Use `custom` for user-defined structs, `struct` for inline struct definitions,
// `array` for slices, `map` for maps, and `any` for untyped/interface values.
type DataType string

// Endpoint A specific entry or exit point on a data connector — an HTTP route, a Kafka topic,
// or a gRPC method. Each Input or Sink stream node references exactly one endpoint.
// The endpoint determines the handler interface that the code generator produces.
type Endpoint struct {
	// ActivityHeartbeatTimeout Temporal Activity heartbeat timeout in milliseconds; zero disables it.
	ActivityHeartbeatTimeout *int `json:"activityHeartbeatTimeout,omitempty"`

	// ActivityStartToCloseTimeout Temporal Activity start-to-close timeout in milliseconds.
	ActivityStartToCloseTimeout *int `json:"activityStartToCloseTimeout,omitempty"`

	// ConsumerGroup Kafka consumer group ID. Applies to Kafka source endpoints.
	ConsumerGroup *string `json:"consumerGroup,omitempty"`

	// CreateTopic When true, the generated service attempts to create the Kafka topic on startup if it does not exist.
	CreateTopic *bool `json:"createTopic,omitempty"`

	// Enabled Controls whether an endpoint starts its transport integration.
	// When omitted or false, the endpoint remains in the execution graph but its
	// external transport or scheduler is not started.
	Enabled *bool `json:"enabled,omitempty"`

	// FunctionDescription Doc comment added to the generated handler struct.
	FunctionDescription *string `json:"functionDescription,omitempty"`

	// FunctionInitializerGroup Initializer group for dependency injection of the generated handler.
	FunctionInitializerGroup *string `json:"functionInitializerGroup,omitempty"`

	// FunctionModule Name of a module defined in `StreamApp.modules`. When set (and `publicFunction: true`),
	// the generated handler is placed in that module instead of the service module.
	FunctionModule *string `json:"functionModule,omitempty"`

	// FunctionName Name of the generated Go handler struct for this endpoint.
	FunctionName *string `json:"functionName,omitempty"`

	// FunctionPackage Subdirectory under the functions package where the generated handler is placed.
	FunctionPackage *string `json:"functionPackage,omitempty"`

	// GrpcMethodType gRPC streaming mode for a gRPC endpoint. Determines the generated handler signature
	// and the streaming behavior of the connector.
	// - `NoStreaming` (1): unary RPC
	// - `ClientStreaming` (2): client sends a stream, server replies once
	// - `ServerStreaming` (4): client sends once, server replies with a stream
	// - `BidirectionalStreaming` (5): both sides stream concurrently
	GrpcMethodType *GrpcMethodType `json:"grpcMethodType,omitempty"`

	// HttpMethodType HTTP verb for an HTTP endpoint.
	HttpMethodType *HTTPMethodType `json:"httpMethodType,omitempty"`

	// Id Unique identifier for this endpoint within the topology.
	Id int `json:"id"`

	// IdDataConnector ID of the data connector this endpoint belongs to.
	IdDataConnector int `json:"idDataConnector"`

	// MaximumAttempts Maximum Temporal Activity attempts including the initial attempt.
	MaximumAttempts *int `json:"maximumAttempts,omitempty"`

	// MethodName gRPC method name as defined in the proto file. Applies to gRPC endpoints.
	MethodName *string `json:"methodName,omitempty"`

	// MissedRunPolicy Portable policy for a firing delayed while the scheduler process is running.
	MissedRunPolicy *ScheduleMissedRunPolicy `json:"missedRunPolicy,omitempty"`

	// Name Human-readable endpoint name shown in the visual designer.
	Name string `json:"name"`

	// OverlapPolicy Portable policy for a firing that overlaps a still-running firing.
	OverlapPolicy *ScheduleOverlapPolicy `json:"overlapPolicy,omitempty"`

	// Partitions Number of partitions for the Kafka topic (used when createTopic is true).
	Partitions *int `json:"partitions,omitempty"`

	// Path URL path for HTTP endpoints (e.g. `/api/v1/orders`). Applies to HTTP connectors.
	Path *string `json:"path,omitempty"`

	// PublicFunction When true, the generated handler is placed in the shared `pkg/functions` tree
	// and can be imported by other services. When false, it goes into `internal/functions`.
	PublicFunction *bool `json:"publicFunction,omitempty"`

	// ReplicationFactor Kafka topic replication factor (used when createTopic is true).
	ReplicationFactor *int `json:"replicationFactor,omitempty"`

	// Schedule Cron expression for a local Cron endpoint or an optional Temporal Schedule.
	Schedule *string `json:"schedule,omitempty"`

	// ScheduleId Immutable Temporal Schedule ID. Required when a Temporal endpoint has a schedule.
	ScheduleId *string `json:"scheduleId,omitempty"`

	// TaskQueue Temporal Task Queue used by this durable endpoint.
	TaskQueue *string `json:"taskQueue,omitempty"`

	// Timezone Timezone used to evaluate the schedule. The portable contract accepts only UTC.
	Timezone *string `json:"timezone,omitempty"`

	// Topic Kafka topic name. Applies to Kafka endpoints.
	Topic *string `json:"topic,omitempty"`

	// WorkflowExecutionTimeout Temporal Workflow execution timeout in milliseconds; zero means SDK default.
	WorkflowExecutionTimeout *int `json:"workflowExecutionTimeout,omitempty"`
}

// Environment Deployment environment for the service. Controls which observability engines
// are selected in the generated bootstrap code.
// - `local`: local developer machine; human-readable logs and tracing, Prometheus metrics
// - `debug`: same as local but with verbose/debug-level output
// - `staging`: pre-production; structured logs and tracing exported via OTLP, Prometheus metrics
// - `production`: live traffic; structured logs and tracing exported via OTLP, Prometheus metrics
type Environment string

// GrpcMethodType gRPC streaming mode for a gRPC endpoint. Determines the generated handler signature
// and the streaming behavior of the connector.
// - `NoStreaming` (1): unary RPC
// - `ClientStreaming` (2): client sends a stream, server replies once
// - `ServerStreaming` (4): client sends once, server replies with a stream
// - `BidirectionalStreaming` (5): both sides stream concurrently
type GrpcMethodType int

// HTTPMethodType HTTP verb for an HTTP endpoint.
type HTTPMethodType string

// JoinStorageType Storage backend used to hold join state while waiting for matching keys from both streams.
type JoinStorageType int

// JoinType Join semantics for Join and MultiJoin operators — controls which combinations of matching keys produce output.
type JoinType int

// KafkaSaslMechanism Kafka SASL authentication mechanism.
type KafkaSaslMechanism string

// KafkaSecurityProtocol Kafka client transport security protocol.
type KafkaSecurityProtocol string

// KubernetesWorkloadType Kubernetes workload controller generated for a service.
type KubernetesWorkloadType string

// Link A directed edge in the topology graph connecting two stream nodes.
// Links carry data from the upstream node (`from`) to the downstream node (`to`)
// according to the specified delivery semantics.
type Link struct {
	// ActivityHeartbeatTimeout Temporal Activity heartbeat timeout in milliseconds; zero disables it.
	ActivityHeartbeatTimeout *int `json:"activityHeartbeatTimeout,omitempty"`

	// ActivityStartToCloseTimeout Temporal Activity start-to-close timeout in milliseconds for this DurableCall link.
	ActivityStartToCloseTimeout *int `json:"activityStartToCloseTimeout,omitempty"`

	// Async Value returned by the caller's `IsAsync`/`isAsync` method when
	// `callSemantics` is `FunctionCall`. Ignored for all other call semantics.
	Async *bool `json:"async,omitempty"`

	// CallSemantics Delivery semantics for a stream link — controls how messages are passed between nodes.
	// - `Inherited` (1): use the service's `defaultCallSemantics`
	// - `FunctionCall` (2): synchronous in-goroutine call; lowest latency, no buffering
	// - `TaskPool` (3): enqueue to a named FIFO worker pool; decouples producer from consumer
	// - `PriorityTaskPool` (4): enqueue to a named priority worker pool; higher-priority messages are processed first
	// - `ParallelCall` (5): spawn a new goroutine for each message; fully parallel, no pool overhead
	// - `DurableCall` (6): execute the link as an independently identified Temporal Workflow/Activity operation
	CallSemantics CallSemantics `json:"callSemantics"`

	// From ID of the upstream (producer) stream node.
	From int `json:"from"`

	// IdDataConnector Temporal data connector used when `callSemantics` is `DurableCall`.
	// Ignored for every other call semantics.
	IdDataConnector *int `json:"idDataConnector,omitempty"`

	// MaximumAttempts Maximum Temporal Activity attempts including the initial attempt.
	MaximumAttempts *int `json:"maximumAttempts,omitempty"`

	// PoolName Name of the worker pool to use when `callSemantics` is `TaskPool` or `PriorityTaskPool`.
	// Must match a pool defined in `StreamApp.pools`.
	PoolName *string `json:"poolName,omitempty"`

	// Priority Message priority for `PriorityTaskPool` delivery. Higher values are processed first.
	// Ignored for other call semantics.
	Priority *int `json:"priority,omitempty"`

	// TaskQueue Temporal Task Queue used by this DurableCall link.
	TaskQueue *string `json:"taskQueue,omitempty"`

	// To ID of the downstream (consumer) stream node.
	To int `json:"to"`

	// WorkflowExecutionTimeout Temporal Workflow execution timeout in milliseconds; zero means SDK default.
	WorkflowExecutionTimeout *int `json:"workflowExecutionTimeout,omitempty"`
}

// LogLevel Logging verbosity for the service runtime.
type LogLevel string

// Module A separate Go module used to host public (shared) functions.
// When a stream node or endpoint has `publicFunction: true` and references this module
// via `functionModule`, its generated stub is placed in this module's package tree
// rather than the owning service's module. This enables shared business logic to be
// imported by multiple services without circular dependencies.
type Module struct {
	// GolangVersion Minimum Go version required for this module (e.g. `1.22`).
	GolangVersion string `json:"golangVersion"`

	// ModulePath Go module path (e.g. `github.com/example/shared`). Used as the base import path for generated packages.
	ModulePath string `json:"modulePath"`

	// Name Module identifier. Referenced by `Stream.functionModule` and `Endpoint.functionModule`.
	Name string `json:"name"`
}

// Pool A named worker pool used for async or priority-based stream delivery.
// Referenced by links with `callSemantics: TaskPool` or `callSemantics: PriorityTaskPool`.
type Pool struct {
	// ExecutorsCount Number of worker goroutines in the pool.
	ExecutorsCount int `json:"executorsCount"`

	// Name Pool name. Referenced in Link.poolName.
	Name string `json:"name"`

	// QueueCapacity Initial capacity of the task queue. Defaults to 256 if not set.
	QueueCapacity *int `json:"queueCapacity,omitempty"`
}

// ProcessPattern Execution pattern for the Process operator — controls how the handler interacts
// with its output stream.
// - `Execute` (1): handler performs a side effect and may emit zero or more results synchronously
// - `Collect` (2): handler accumulates results and emits them in batch
type ProcessPattern int

// ProgrammingLanguage Target programming language for code generation.
type ProgrammingLanguage int

// ProjectSettings Global metadata for the topology project.
type ProjectSettings struct {
	// ModuleVersion Semantic version tag used when publishing modules to Git (e.g. `v0.2.2`). Defaults to `v0.2.2`.
	ModuleVersion *string `json:"moduleVersion,omitempty"`

	// Name Human-readable project name. Used in generated file headers.
	Name string `json:"name"`

	// RepoPath Git repository path for the project itself (e.g. `github.com/example/myproject`). When set, `make init` and `make git-push` will also push the project root to this remote.
	RepoPath *string `json:"repoPath,omitempty"`
}

// ScheduleMissedRunPolicy Portable policy for a firing delayed while the scheduler process is running.
type ScheduleMissedRunPolicy string

// ScheduleOverlapPolicy Portable policy for a firing that overlaps a still-running firing.
type ScheduleOverlapPolicy string

// Service A single microservice in the topology. Each stream node belongs to exactly one service.
// The service defines the runtime configuration (ports, timeouts, logging) and the
// Go module path used for code generation.
type Service struct {
	// Color Hex color code used to represent this service in the visual topology designer.
	Color string `json:"color"`

	// DefaultCallSemantics Delivery semantics for a stream link — controls how messages are passed between nodes.
	// - `Inherited` (1): use the service's `defaultCallSemantics`
	// - `FunctionCall` (2): synchronous in-goroutine call; lowest latency, no buffering
	// - `TaskPool` (3): enqueue to a named FIFO worker pool; decouples producer from consumer
	// - `PriorityTaskPool` (4): enqueue to a named priority worker pool; higher-priority messages are processed first
	// - `ParallelCall` (5): spawn a new goroutine for each message; fully parallel, no pool overhead
	// - `DurableCall` (6): execute the link as an independently identified Temporal Workflow/Activity operation
	DefaultCallSemantics CallSemantics `json:"defaultCallSemantics"`

	// DefaultGrpcTimeout Default gRPC call timeout in milliseconds.
	DefaultGrpcTimeout int `json:"defaultGrpcTimeout"`

	// Environment Deployment environment for the service. Controls which observability engines
	// are selected in the generated bootstrap code.
	// - `local`: local developer machine; human-readable logs and tracing, Prometheus metrics
	// - `debug`: same as local but with verbose/debug-level output
	// - `staging`: pre-production; structured logs and tracing exported via OTLP, Prometheus metrics
	// - `production`: live traffic; structured logs and tracing exported via OTLP, Prometheus metrics
	Environment Environment `json:"environment"`

	// GolangVersion Minimum Go version required for the generated module (e.g. `1.22`).
	GolangVersion *string `json:"golangVersion,omitempty"`

	// GrpcHost Host address for the service's gRPC server.
	GrpcHost string `json:"grpcHost"`

	// GrpcPort Port for the service's gRPC server.
	GrpcPort int `json:"grpcPort"`

	// HttpHost Host address for the service's HTTP server.
	HttpHost string `json:"httpHost"`

	// HttpPort Port for the service's HTTP server.
	HttpPort int `json:"httpPort"`

	// Id Unique identifier for the service within the topology.
	Id int `json:"id"`

	// KubernetesWorkloadType Kubernetes workload controller generated for a service.
	KubernetesWorkloadType KubernetesWorkloadType `json:"kubernetesWorkloadType"`

	// LivenessHandler URL path for the Kubernetes liveness probe. Leave empty to disable.
	LivenessHandler string `json:"livenessHandler"`

	// LogLevel Logging verbosity for the service runtime.
	LogLevel *LogLevel `json:"logLevel,omitempty"`

	// MetricsHandler URL path for the Prometheus metrics endpoint (e.g. `/metrics`).
	// Leave empty to disable.
	MetricsHandler string `json:"metricsHandler"`

	// ModulePath Go module path (e.g. `github.com/example/myservice`). Used as the base import path
	// for all generated packages within this service.
	ModulePath string `json:"modulePath"`

	// Name Human-readable service name. Used as the root directory name for generated code.
	Name string `json:"name"`

	// ProgrammingLanguage Target programming language for code generation.
	ProgrammingLanguage ProgrammingLanguage `json:"programmingLanguage"`

	// ReadinessHandler URL path for the Kubernetes readiness probe. Leave empty to disable.
	ReadinessHandler string `json:"readinessHandler"`

	// ShutdownTimeout Maximum time in milliseconds to wait for graceful shutdown before forcing termination.
	ShutdownTimeout int `json:"shutdownTimeout"`

	// StartupHandler URL path for the Kubernetes startup probe. Leave empty to disable.
	StartupHandler string `json:"startupHandler"`

	// StatusHandler URL path for the built-in topology visualization endpoint (e.g. `/status`).
	// When set, the service serves a live dataflow graph with real-time call counts.
	// Leave empty to disable.
	StatusHandler string `json:"statusHandler"`
}

// Stream A node in the topology dataflow graph. Each stream node represents one operator
// (transformation, source, sink, or routing construct). The `type` field determines
// the operator and therefore the signature of the generated Go stub.
type Stream struct {
	// Duration Fixed delay duration in milliseconds for the Delay operator.
	// Used when the delay is not computed per-element.
	Duration *int `json:"duration,omitempty"`

	// FunctionDescription Doc comment added to the generated struct. Describe the node's business purpose here.
	FunctionDescription *string `json:"functionDescription,omitempty"`

	// FunctionInitializerGroup Initializer group name for dependency injection. Stubs in the same group
	// are initialized together. Used by the generated service bootstrap code.
	FunctionInitializerGroup *string `json:"functionInitializerGroup,omitempty"`

	// FunctionModule Name of a module defined in `StreamApp.modules`. When set (and `publicFunction: true`),
	// the generated stub is placed in that module's package tree instead of the service module.
	// Used to share business logic across multiple services.
	FunctionModule *string `json:"functionModule,omitempty"`

	// FunctionName Name of the generated Go struct for this node's business logic implementation.
	// The code generator produces a stub with this name that the developer implements.
	FunctionName *string `json:"functionName,omitempty"`

	// FunctionPackage Subdirectory under the functions package where the generated stub is placed
	// (e.g. `handlers`, `transforms`). Omit for the default functions package root.
	FunctionPackage *string `json:"functionPackage,omitempty"`

	// Id Unique identifier for this stream node within the topology.
	Id int `json:"id"`

	// IdEndpoint ID of the associated endpoint. Required for Input and Sink nodes;
	// determines which data connector entry/exit point this node uses.
	IdEndpoint *int `json:"idEndpoint,omitempty"`

	// IdService ID of the service this node belongs to.
	IdService int `json:"idService"`

	// IdSource ID of the single upstream stream node. Used by operators with one input
	// (Map, Filter, FlatMap, Process, KeyBy, Split, Case, Delay, Sink).
	// Set to 0 when the node has no single source (Input nodes, Merge, MultiJoin).
	IdSource int `json:"idSource"`

	// IdSources IDs of multiple upstream stream nodes. Used by Merge (same type, N sources)
	// and MultiJoin (keyed streams, N sources). Mutually exclusive with `idSource`
	// for these operator types.
	IdSources *[]int `json:"idSources,omitempty"`

	// JoinStorage Storage backend used to hold join state while waiting for matching keys from both streams.
	JoinStorage *JoinStorageType `json:"joinStorage,omitempty"`

	// JoinType Join semantics for Join and MultiJoin operators — controls which combinations of matching keys produce output.
	JoinType *JoinType `json:"joinType,omitempty"`

	// KeyType Name of the key type for keyed stream nodes (KeyBy, Join, MultiJoin).
	// Must be a comparable Go type.
	KeyType *string `json:"keyType,omitempty"`

	// Name Human-readable node name shown in the visual designer.
	Name string `json:"name"`

	// Pattern Execution pattern for the Process operator — controls how the handler interacts
	// with its output stream.
	// - `Execute` (1): handler performs a side effect and may emit zero or more results synchronously
	// - `Collect` (2): handler accumulates results and emits them in batch
	Pattern *ProcessPattern `json:"pattern,omitempty"`

	// Pipeline Stream pipeline name
	Pipeline *string `json:"pipeline,omitempty"`

	// PublicFunction When true, this node's stub is placed in the shared `pkg/functions` tree
	// (or in a separate module if `functionModule` is set) and can be imported
	// by other services. When false, it goes into the service's `internal/functions` tree.
	PublicFunction *bool `json:"publicFunction,omitempty"`

	// RenewTTL When true, the TTL is reset each time a new element arrives for a key,
	// keeping the state alive as long as data keeps flowing. Applies to Join and MultiJoin.
	RenewTTL *bool `json:"renewTTL,omitempty"`

	// Ttl Join state time-to-live in milliseconds. After this duration without a matching key
	// from the other stream, the accumulated state is discarded. Applies to Join and MultiJoin.
	Ttl *int `json:"ttl,omitempty"`

	// Type The operator type for a stream node. Determines the node's role in the dataflow graph
	// and the signature of the generated stub.
	//
	// - `Input` (1): ingests data from an external source via a data connector endpoint
	// - `Map` (2): transforms each element T → R
	// - `Filter` (3): discards elements that do not satisfy a predicate
	// - `Join` (4): combines two keyed streams (KeyValue[K,T1] + KeyValue[K,T2] → R)
	// - `MultiJoin` (5): combines N keyed streams into a single output
	// - `Process` (6): transforms T → R with a side-output error stream E
	// - `FlatMap` (7): expands one element T into zero or more R
	// - `FlatMapIterable` (8): expands T into an iterable of R without a user function
	// - `KeyBy` (9): partitions a stream into keyed sub-streams (T → KeyValue[K,V])
	// - `Merge` (10): merges multiple streams of the same type T
	// - `Split` (11): broadcasts one stream to multiple downstream consumers
	// - `Case` (12): routes each element to one of N typed branches (switch/case)
	// - `Sink` (13): sends data to an external destination via a data connector endpoint
	// - `CycleLink` (14): feeds output back into an earlier node in the graph
	// - `Error` (15): receives error elements from a Process node's error output
	// - `Delay` (16): defers downstream delivery by a computed duration
	// - `When` (17): a typed branch of a Case node
	Type TransformationType `json:"type"`

	// ValueType Name of the output message type for this node (e.g. `OrderEvent`).
	// Must match a type defined in `StreamApp.types` or an imported Go type.
	ValueType *string `json:"valueType,omitempty"`

	// XPos Horizontal position of the node in the visual designer canvas.
	XPos float32 `json:"xPos"`

	// YPos Vertical position of the node in the visual designer canvas.
	YPos float32 `json:"yPos"`
}

// StreamApp The complete topology definition for a distributed service system.
// This is the root document submitted to the code generator.
// It describes the full dataflow graph: which services exist, how streams connect,
// what external systems are involved, and what data types flow through the graph.
type StreamApp struct {
	// DataConnectors External system connections (HTTP servers, Kafka clusters, gRPC servers).
	DataConnectors []DataConnector `json:"dataConnectors"`

	// Endpoints Specific entry or exit points on a data connector (routes, topics, methods).
	Endpoints []Endpoint `json:"endpoints"`

	// Links Directed edges connecting stream nodes. Each link carries data from one node to the next.
	Links []Link `json:"links"`

	// Modules Additional Go modules for shared public functions. When a stream or endpoint
	// has `publicFunction: true` and references a module here via `functionModule`,
	// generated stubs are placed in that module's package tree rather than the
	// service's own module.
	Modules *[]Module `json:"modules,omitempty"`

	// Pools Named worker pools used for async or priority-based stream delivery.
	Pools []Pool `json:"pools"`

	// Services Microservices that participate in the topology.
	Services []Service `json:"services"`

	// Settings Global metadata for the topology project.
	Settings ProjectSettings `json:"settings"`

	// Streams All stream nodes (operators) in the topology graph.
	Streams []Stream `json:"streams"`

	// Types Named data types used as message types across the graph.
	Types []Type `json:"types"`

	// UndefinedEnum Sentinel value used to represent an undefined/unset enum. Always 0.
	UndefinedEnum *UndefinedEnum `json:"undefinedEnum,omitempty"`
}

// TransformationType The operator type for a stream node. Determines the node's role in the dataflow graph
// and the signature of the generated stub.
//
// - `Input` (1): ingests data from an external source via a data connector endpoint
// - `Map` (2): transforms each element T → R
// - `Filter` (3): discards elements that do not satisfy a predicate
// - `Join` (4): combines two keyed streams (KeyValue[K,T1] + KeyValue[K,T2] → R)
// - `MultiJoin` (5): combines N keyed streams into a single output
// - `Process` (6): transforms T → R with a side-output error stream E
// - `FlatMap` (7): expands one element T into zero or more R
// - `FlatMapIterable` (8): expands T into an iterable of R without a user function
// - `KeyBy` (9): partitions a stream into keyed sub-streams (T → KeyValue[K,V])
// - `Merge` (10): merges multiple streams of the same type T
// - `Split` (11): broadcasts one stream to multiple downstream consumers
// - `Case` (12): routes each element to one of N typed branches (switch/case)
// - `Sink` (13): sends data to an external destination via a data connector endpoint
// - `CycleLink` (14): feeds output back into an earlier node in the graph
// - `Error` (15): receives error elements from a Process node's error output
// - `Delay` (16): defers downstream delivery by a computed duration
// - `When` (17): a typed branch of a Case node
type TransformationType int

// Type A named data type used as a message type in the topology graph.
// Types are referenced by stream nodes via `valueType` and `keyType`.
// The code generator uses the type definition to produce correct Go type references
// and import statements in generated stubs.
type Type struct {
	// DefinitionFormat Serialization format used for the type definition. Determines how the type
	// is serialized/deserialized when crossing process or network boundaries.
	// - `Native` (1): language-native encoding (Go encoding/json, etc.)
	// - `Protobuf` (2): Protocol Buffers
	// - `FlatBuffers` (3): FlatBuffers
	// - `CapNProto` (4): Cap'n Proto
	// - `OpenAPI` (5): JSON encoding for types generated from an OpenAPI spec (oapi-codegen)
	DefinitionFormat *TypeDefinitionFormat `json:"definitionFormat,omitempty"`

	// Description Human-readable description of this type. Used as a doc comment in generated code.
	Description *string `json:"description,omitempty"`

	// KeyType Key type for `map` composite types.
	KeyType *string `json:"keyType,omitempty"`

	// Module Name of a module defined in `StreamApp.modules` that owns this type.
	// Used to resolve the correct import path when `publicType: true`.
	Module *string `json:"module,omitempty"`

	// Name Unique type name referenced by streams (e.g. `OrderEvent`, `UserProfile`).
	Name string `json:"name"`

	// Package Go package name alias used in generated import statements when it differs from the last path component.
	Package *string `json:"package,omitempty"`

	// PublicType When true, this type is shared across services and placed in the shared types package.
	PublicType *bool `json:"publicType,omitempty"`

	// TransferByValue When true, the type is passed by value in generated function signatures.
	// When false (default), it is passed as a pointer.
	TransferByValue *bool `json:"transferByValue,omitempty"`

	// Type Primitive or composite data type for a named type. Controls generated serde code
	// and type compatibility checks within the graph.
	// Use `custom` for user-defined structs, `struct` for inline struct definitions,
	// `array` for slices, `map` for maps, and `any` for untyped/interface values.
	Type DataType `json:"type"`

	// TypeDefinitionLang1 Inline type definition for GoLang (e.g. `interface{}`, `map[string]int`). Used when the type has no external package.
	TypeDefinitionLang1 *string `json:"typeDefinitionLang1,omitempty"`

	// TypeDefinitionLang2 Inline type definition for C++ (e.g. `std::any`).
	TypeDefinitionLang2 *string `json:"typeDefinitionLang2,omitempty"`

	// TypeImportLang1 Go import path for the package that defines this type (e.g. `github.com/example/types`).
	TypeImportLang1 *string `json:"typeImportLang1,omitempty"`

	// TypeImportLang2 C++ include path for the header that defines this type.
	TypeImportLang2 *string `json:"typeImportLang2,omitempty"`

	// UseAlias When true, the generated Go code uses a type alias instead of a full struct definition.
	UseAlias *bool `json:"useAlias,omitempty"`

	// ValueType Element type for `array` and value type for `map` composite types.
	ValueType *string `json:"valueType,omitempty"`
}

// TypeDefinitionFormat Serialization format used for the type definition. Determines how the type
// is serialized/deserialized when crossing process or network boundaries.
// - `Native` (1): language-native encoding (Go encoding/json, etc.)
// - `Protobuf` (2): Protocol Buffers
// - `FlatBuffers` (3): FlatBuffers
// - `CapNProto` (4): Cap'n Proto
// - `OpenAPI` (5): JSON encoding for types generated from an OpenAPI spec (oapi-codegen)
type TypeDefinitionFormat int

// UndefinedEnum Sentinel value used to represent an undefined/unset enum. Always 0.
type UndefinedEnum int

// PostGenerateCodeJSONRequestBody defines body for PostGenerateCode for application/json ContentType.
type PostGenerateCodeJSONRequestBody = StreamApp

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Generate typed Go stubs from a topology definition.
	// (POST /generateCode)
	PostGenerateCode(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostGenerateCode operation middleware
func (siw *ServerInterfaceWrapper) PostGenerateCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGenerateCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/generateCode", wrapper.PostGenerateCode)

	return m
}
